import Head from 'next/head'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import WorkExperience from '@/components/WorkExperience'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import ContactMe from '@/components/ContactMe'
import Link from 'next/link'
import { ChevronDoubleUpIcon } from '@heroicons/react/24/outline'
import { PageInfo, Experience, Skill, Project, Social } from '../../typings'
import { fetchPageInfo } from '../../utils/fetchPageInfo'
import { fetchSkills } from '../../utils/fetchSkills'
import { fetchExperience } from '../../utils/fetchExperience'
import { fetchProjects } from '../../utils/fetchProjects'
import { fetchSocials } from '../../utils/fetchSocials'
// import { GetServerSideProps, GetStaticProps } from 'next/types'
import 'react-tooltip/dist/react-tooltip.css'


type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}

export async function getServerSideProps() {
  let res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/getPageInfo`)
  let data = await res.json()
  const pageInfo: PageInfo = data.pageInfo;

  res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/getSkills`)
  data = await res.json()
  const skills: Skill[] = data.skills;

  res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/getExperience`)
  data = await res.json()
  const experiences: Experience[] = data.experiences;

  res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/getProjects`)
  data = await res.json()
  const projects: Project[] = data.projects;

  res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/getSocials`)
  data = await res.json()
  const socials: Social[] = data.socials;

  return {
    props: {
      pageInfo, skills, experiences, projects, socials
    },
  }
}
 
export default function Home(
  {
    pageInfo, experiences, skills, projects, socials
  }: any) {
  return (
    <div className='bg-[rgb(36,36,36)] text-white snap-y snap-mandatory overflow-y-scroll z-0
    overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80' 
    style={{zoom: "67%", height: "150vh"}}>
      <Head>
        <title>Fajar's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      <section id='hero' className='snap-start'>
        <Hero pageInfo={pageInfo}/>
      </section>

      <section id='about' className='snap-center'>
        <About pageInfo={pageInfo}/>
      </section>

      <section id='experience' className='snap-center'>
        <WorkExperience experiences={experiences}/>
      </section>

      <section id='skills' className='snap-start'>
        <Skills skills={skills}/>
      </section>

      <section id='projects' className='snap-start'>
        <Projects projects={projects}/>
      </section>

      <section id='contact' className='snap-center'>
        <ContactMe pageInfo={pageInfo}/>
      </section>

      <Link href="#hero">
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <ChevronDoubleUpIcon className='h-10 w-10 rounded-full filter grayscale
            hover:grayscale-0 cursor-pointer' />
          </div>
        </footer>
      </Link>
    </div>
  )
}

